svn:
	@touch config.rpath
	@echo "*** Synchronizing libtool..."
	@libtoolize --force
	@echo "*** Retrieving configure tests needed by configure.in..."
	@aclocal
	@echo "*** Building Makefile templates (step one)..."
	@automake --add-missing
	@automake
	@echo "*** Building Makefile templates (step two)..."
	@autoconf
	@echo "*** Finished"
	@echo "    Don't forget to run ./configure"
	@echo "    If you haven't done so in a while, run ./configure --help"


